# S04
# bool slot04_Q1_bumperreset #not work
# bool slot04_Q2_resetlight #not work
bool slot04_Q3_sigleslotheadlight
# S06
uint16 back_2D_group
# S07
uint16 front_2D_group
# S08
uint16 right_2D_group
# S09
uint16 left_2D_group
# S10
bool slot10_IY7_chargerboard
bool slot10_IY8_rightturnsignal
bool slot10_Y1_leftturnsignal
bool slot11_IY7_rightdistancedetection
bool slot11_IY8_leftdistancedetection
bool slot11_Y1_RGBflash_red
bool slot11_Y2_RGBflash_yellow
bool slot11_Y3_RGBflash_green
bool slot11_Y4_RGBflash_buzzer1
bool slot11_Y4_RGBflash_buzzer2
bool slot11_Y4_RGBflash_buzzer3